DROP TABLE IF EXISTS consulta CASCADE;
DROP TABLE IF EXISTS medico_convenio CASCADE;
DROP TABLE IF EXISTS medico_especialidade CASCADE;
DROP TABLE IF EXISTS paciente CASCADE;
DROP TABLE IF EXISTS medico CASCADE;
DROP TABLE IF EXISTS especialidade CASCADE;
DROP TABLE IF EXISTS convenio CASCADE;

CREATE TABLE convenio (
    id_convenio INT GENERATED BY DEFAULT AS IDENTITY,
    nome_convenio VARCHAR(100) NOT NULL,

    CONSTRAINT pk_convenio PRIMARY KEY (id_convenio),
    CONSTRAINT uq_convenio_nome UNIQUE (nome_convenio)
);

CREATE TABLE especialidade (
    id_especialidade INT GENERATED BY DEFAULT AS IDENTITY,
    nome_especialidade VARCHAR(100) NOT NULL,

    CONSTRAINT pk_especialidade PRIMARY KEY (id_especialidade),
    CONSTRAINT uq_especialidade_nome UNIQUE (nome_especialidade)
);

CREATE TABLE medico (
    id_medico INT GENERATED BY DEFAULT AS IDENTITY,
    nome_medico VARCHAR(255) NOT NULL,
    crm VARCHAR(20) NOT NULL,

    CONSTRAINT pk_medico PRIMARY KEY (id_medico),
    CONSTRAINT uq_medico_crm UNIQUE (crm)
);

CREATE TABLE paciente (
    id_paciente INT GENERATED BY DEFAULT AS IDENTITY,
    nome_paciente VARCHAR(255) NOT NULL,
    cpf VARCHAR(11) NOT NULL,
    data_nascimento DATE NOT NULL,
    id_convenio INT NOT NULL,

    CONSTRAINT pk_paciente PRIMARY KEY (id_paciente),
    CONSTRAINT uq_paciente_cpf UNIQUE (cpf),
    CONSTRAINT fk_paciente_convenio FOREIGN KEY (id_convenio) 
        REFERENCES convenio (id_convenio)
);

CREATE TABLE medico_especialidade (
    id_medico INT NOT NULL,
    id_especialidade INT NOT NULL,

    CONSTRAINT pk_medico_especialidade PRIMARY KEY (id_medico, id_especialidade),
    CONSTRAINT fk_me_medico FOREIGN KEY (id_medico) 
        REFERENCES medico (id_medico),
    CONSTRAINT fk_me_especialidade FOREIGN KEY (id_especialidade) 
        REFERENCES especialidade (id_especialidade)
);

CREATE TABLE medico_convenio (
    id_medico INT NOT NULL,
    id_convenio INT NOT NULL,

    CONSTRAINT pk_medico_convenio PRIMARY KEY (id_medico, id_convenio),
    CONSTRAINT fk_mc_medico FOREIGN KEY (id_medico) 
        REFERENCES medico (id_medico),
    CONSTRAINT fk_mc_convenio FOREIGN KEY (id_convenio) 
        REFERENCES convenio (id_convenio)
);

CREATE TABLE consulta (
    id_consulta INT GENERATED BY DEFAULT AS IDENTITY,
    id_paciente INT NOT NULL,
    id_medico INT NOT NULL,
    id_especialidade INT NOT NULL,
    data_hora TIMESTAMP NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'AGENDADA',

    CONSTRAINT pk_consulta PRIMARY KEY (id_consulta),

    CONSTRAINT fk_consulta_paciente FOREIGN KEY (id_paciente) 
        REFERENCES paciente (id_paciente),
    CONSTRAINT fk_consulta_medico FOREIGN KEY (id_medico) 
        REFERENCES medico (id_medico),

    CONSTRAINT fk_consulta_medico_espec FOREIGN KEY (id_medico, id_especialidade) 
        REFERENCES medico_especialidade (id_medico, id_especialidade),

    CONSTRAINT uq_medico_horario UNIQUE (id_medico, data_hora), -- RN03
    CONSTRAINT uq_paciente_horario UNIQUE (id_paciente, data_hora), -- RN04

    CONSTRAINT ck_consulta_status CHECK (status IN ('AGENDADA', 'CONFIRMADA', 'CANCELADA', 'REALIZADA')) -- RN07
);

CREATE INDEX idx_consulta_data_hora ON consulta(data_hora);
CREATE INDEX idx_consulta_id_medico ON consulta(id_medico);